# Generated by Django 5.1.7 on 2025-05-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
